### ISSUE TITLE
Can't compile to ESP32

### ISSUE THREAD

**Issue by morcibacsi** [0xCAFEDECAF/VanBus#1]
Hi,
I am here to report the first issue :)

I was trying to compile it to an ESP32 dev board, but it has different methods for the timers, so the following errors occured:

![image](https://user-images.githubusercontent.com/6507173/85943769-745d5b00-b932-11ea-9e43-ad1ba05250a3.png)

Compiling to ESP8266 was ok.

**Comment by 0xCAFEDECAF** [comment]
Ah, forgot to test. Indeed those functions are 8266 specific.

I will check later for the generic functions. For now I updated the master branch by removing the mentioning of ESP32.

Thanks!

**Comment by 0xCAFEDECAF** [comment]
Removed the ESP32 from the list of supported hardware; created new release V0.1.1.
