### ISSUE TITLE
MCP2515 SPI

### ISSUE THREAD

**Issue by Antonzlo** [0xCAFEDECAF/VanBus#10]
Hi, is there a native way to use it? Or does it require to rewrite half of the library? 🙂

**Comment by 0xCAFEDECAF** [comment]
You mean this one: https://ww1.microchip.com/downloads/en/DeviceDoc/MCP2515-Stand-Alone-CAN-Controller-with-SPI-20001801J.pdf ? That is for CAN bus. It will not work for VAN bus because the layout of the bits is different.

**Comment by Antonzlo** [comment]
Okay, thanks. But 2551 works? How to know what else works?

**Comment by 0xCAFEDECAF** [comment]
Yes, [MCP2551 works](https://github.com/0xCAFEDECAF/VanBus#schematics). Also, the SN65HVD230 transceiver works. You could also try the [Atmel TSS463/TSS461 VAN Datalink Controller](http://ww1.microchip.com/downloads/en/DeviceDoc/doc4205.pdf), but it needs a different library which is found here: https://github.com/morcibacsi/arduino_tss463_van . They are difficult to find for sale.

**Comment by 0xCAFEDECAF** [comment]
Long time no hear; I guess this ticket can be closed.

**Comment by 0xCAFEDECAF** [comment]
Long time no hear; I guess this ticket can be closed.
