### ISSUE TITLE
Are AliExpress's SN65HVD230 boards any good?

### ISSUE THREAD

**Issue by Vincent0690** [0xCAFEDECAF/VanBus#4]
hey
I'm looking for a cheap SN65HVD230 board. My habitual retailer doesn't sell thoses. I found many board for 1-2€ on AE, Amazon list them at 5 to almost 20€.
What link would you recommend?

**Comment by 0xCAFEDECAF** [comment]
I ordered this one: https://webshop.domoticx.nl/index.php?route=product/product&product_id=3935 . A bit more expensive than AE but not as much as you found at Amazon. Delivery was within a few days, but I'm not sure if they will ship to your country.

It works fine. If you have more time you might just as well order at AE. My experience with AE is that the quality of these basic electronics is pretty good.

**Comment by Vincent0690** [comment]
They do ship, but for 25€. I'll go for AE and wait till October 😭

**Comment by bodanius** [comment]
Can I suggest using these product links (shipped from the netherlands):

https://opencircuit.shop/product/sn65hvd230-can-bus-tranceiver-3.3v
https://opencircuit.shop/product/mcp2551-can-bus-interface-module
https://opencircuit.shop/product/voltage-conversion-module-4-channel-5v-3.3v

You could even throw in the latest Wemos to make the list complete:
https://opencircuit.shop/product/wemos-d1-mini-v4.0-wifi-module

**Comment by 0xCAFEDECAF** [comment]
Thanks for the tip!

I noticed https://opencircuit.nl also works.

By the way, https://opencircuit.nl/product/mcp2551-can-bus-interface-module and 
https://opencircuit.nl/product/sn65hvd230-can-bus-tranceiver-3.3v are listed as "out of stock".

**Comment by 0xCAFEDECAF** [comment]
Solved
