### ISSUE TITLE
compile fails error: 'countSatnav' was not declared in this scope

### ISSUE THREAD

**Issue by nona00** [0xCAFEDECAF/VanBus#8]
sketch\VanBusRx.cpp: In member function 'void TVanPacketRxQueue::_AdvanceHead()':
sketch\VanBusRx.cpp:1262:34: error: 'countSatnav' was not declared in this scope
 1262 |     if (_head->IsSatnavPacket()) countSatnav++;  // TODO - remove
      |                                  ^~~~~~~~~~~

**Comment by 0xCAFEDECAF** [comment]
Fixed with commit dfce8b2 . Thanks for noticing :smile:
